name: Unit Tests

on:
  pull_request:
  push:

jobs:
  tests:
    name: tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python 3.x
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r ./requirements.txt

      - name: terraform/python Unit tests
        run: |
          export PYTHONPATH=$PYTHONPATH:$(pwd)
          python -m unittest discover -s terraform/python/rekognition_api/tests/
